# Generated by Django 3.2.10 on 2021-12-23 07:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('strains_supply', '0013_auto_20211222_2231'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='companyBranch',
        ),
        migrations.AddField(
            model_name='profile',
            name='company_branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='strains_supply.companybranch', verbose_name='Филиал'),
        ),
    ]
