# Generated by Django 3.2.4 on 2021-06-25 13:01

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ApplicationScope',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500, verbose_name='Название')),
                ('inserted_at', models.DateTimeField(default=datetime.datetime(2021, 6, 25, 13, 1, 49, 19997, tzinfo=utc), verbose_name='Добавлено')),
                ('inserted_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Добавил')),
            ],
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500, verbose_name='Название')),
                ('inserted_at', models.DateTimeField(default=datetime.datetime(2021, 6, 25, 13, 1, 49, 17576, tzinfo=utc), verbose_name='Добавлено')),
            ],
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500, verbose_name='Название')),
                ('inserted_at', models.DateTimeField(default=datetime.datetime(2021, 6, 25, 13, 1, 49, 16796, tzinfo=utc), verbose_name='Добавлено')),
                ('inserted_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Добавил')),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500, verbose_name='Название')),
                ('inserted_at', models.DateTimeField(default=datetime.datetime(2021, 6, 25, 13, 1, 49, 19419, tzinfo=utc), verbose_name='Добавлено')),
                ('inserted_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Добавил')),
            ],
        ),
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500, verbose_name='Название')),
                ('site', models.CharField(max_length=500, verbose_name='Название')),
                ('activity_description', models.CharField(max_length=500, verbose_name='Краткое описание вида деятельности')),
                ('inserted_at', models.DateTimeField(default=datetime.datetime(2021, 6, 25, 13, 1, 49, 18242, tzinfo=utc), verbose_name='Добавлено')),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organizations.city', verbose_name='Город')),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organizations.country', verbose_name='Страна')),
                ('inserted_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Добавил')),
            ],
        ),
        migrations.CreateModel(
            name='Projects',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500, verbose_name='Название')),
                ('description', models.CharField(max_length=1000, verbose_name='Описание')),
                ('inserted_at', models.DateTimeField(default=datetime.datetime(2021, 6, 25, 13, 1, 49, 20629, tzinfo=utc), verbose_name='Добавлено')),
                ('application_scope', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organizations.applicationscope', verbose_name='Область применения')),
                ('inserted_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Добавил')),
                ('lead_scientist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organizations.employee', verbose_name='Ведущий научный сотрудник')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organizations.organization', verbose_name='Огранизация')),
            ],
        ),
        migrations.CreateModel(
            name='EmployeeRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500, verbose_name='Название')),
                ('inserted_at', models.DateTimeField(default=datetime.datetime(2021, 6, 25, 13, 1, 49, 18873, tzinfo=utc), verbose_name='Добавлено')),
                ('inserted_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Добавил')),
            ],
        ),
        migrations.AddField(
            model_name='employee',
            name='role',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organizations.employeerole', verbose_name='Должность'),
        ),
        migrations.AddField(
            model_name='city',
            name='country',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organizations.country', verbose_name='Страна'),
        ),
        migrations.AddField(
            model_name='city',
            name='inserted_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Добавил'),
        ),
    ]
