# Generated by Django 3.2.4 on 2021-06-25 13:02

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicationscope',
            name='inserted_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Добавлено'),
        ),
        migrations.AlterField(
            model_name='city',
            name='inserted_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Добавлено'),
        ),
        migrations.AlterField(
            model_name='country',
            name='inserted_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Добавлено'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='inserted_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Добавлено'),
        ),
        migrations.AlterField(
            model_name='employeerole',
            name='inserted_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Добавлено'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='inserted_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Добавлено'),
        ),
        migrations.AlterField(
            model_name='projects',
            name='inserted_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Добавлено'),
        ),
    ]
