# Generated by Django 3.2.4 on 2021-06-25 13:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0003_rename_projects_project'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='applicationscope',
            options={'verbose_name': 'Область применения'},
        ),
        migrations.AlterModelOptions(
            name='city',
            options={'verbose_name': 'Города'},
        ),
        migrations.AlterModelOptions(
            name='country',
            options={'verbose_name': 'Страны'},
        ),
        migrations.AlterModelOptions(
            name='employee',
            options={'verbose_name': 'Сотрудники'},
        ),
        migrations.AlterModelOptions(
            name='employeerole',
            options={'verbose_name': 'Должность'},
        ),
        migrations.AlterModelOptions(
            name='organization',
            options={'verbose_name': 'Организации'},
        ),
        migrations.AlterModelOptions(
            name='project',
            options={'verbose_name': 'Проекты'},
        ),
    ]
