# Generated by Django 3.2.4 on 2021-06-28 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0004_auto_20210625_1628'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='applicationscope',
            options={'verbose_name_plural': 'Область применения'},
        ),
        migrations.AlterModelOptions(
            name='city',
            options={'verbose_name_plural': 'Города'},
        ),
        migrations.AlterModelOptions(
            name='country',
            options={'verbose_name_plural': 'Страны'},
        ),
        migrations.AlterModelOptions(
            name='employee',
            options={'verbose_name_plural': 'Сотрудники'},
        ),
        migrations.AlterModelOptions(
            name='employeerole',
            options={'verbose_name_plural': 'Должность'},
        ),
        migrations.AlterModelOptions(
            name='organization',
            options={'verbose_name_plural': 'Организации'},
        ),
        migrations.AlterModelOptions(
            name='project',
            options={'verbose_name_plural': 'Проекты'},
        ),
        migrations.AlterField(
            model_name='organization',
            name='activity_description',
            field=models.CharField(blank=True, max_length=500, verbose_name='Краткое описание вида деятельности'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='site',
            field=models.CharField(max_length=500, verbose_name='Сайт'),
        ),
    ]
