# Generated by Django 3.2.4 on 2021-06-28 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0005_auto_20210628_1507'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='activity_description',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Краткое описание вида деятельности'),
        ),
    ]
