# Generated by Django 3.2.4 on 2021-06-28 12:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0006_alter_organization_activity_description'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='organization',
            unique_together={('country', 'name')},
        ),
    ]
