# Generated by Django 3.2.4 on 2021-06-29 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0007_alter_organization_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='progress',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Прогресс'),
        ),
    ]
