# Generated by Django 3.2.5 on 2021-07-12 21:28

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0010_employee_organization'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='updated_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Обновлено'),
        ),
        migrations.AlterField(
            model_name='project',
            name='progress',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Уровень прогресса'),
        ),
        migrations.AlterField(
            model_name='project',
            name='updated_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Обновлено'),
        ),
        migrations.AddIndex(
            model_name='project',
            index=models.Index(fields=['application_scope', 'description'], name='organizatio_applica_35ff47_idx'),
        ),
    ]
