# Generated by Django 3.2.5 on 2021-07-12 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0011_auto_20210713_0028'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='organization',
            index=models.Index(fields=['activity_description'], name='organizatio_activit_467ecd_idx'),
        ),
    ]
