# Generated by Django 3.2.5 on 2021-07-12 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0012_organization_organizatio_activit_467ecd_idx'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='organization',
            name='organizatio_activit_467ecd_idx',
        ),
        migrations.AddIndex(
            model_name='organization',
            index=models.Index(fields=['activity_description', 'site'], name='organizatio_activit_fc8a9e_idx'),
        ),
    ]
