# Generated by Django 3.2.5 on 2021-07-12 22:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0013_auto_20210713_0059'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='organization',
            name='organizatio_activit_fc8a9e_idx',
        ),
        migrations.RemoveIndex(
            model_name='project',
            name='organizatio_applica_35ff47_idx',
        ),
    ]
