# Generated by Django 3.2.5 on 2021-07-12 22:51
import datetime as dt

from django.db import migrations


def populate_progress(apps, schema_editor):
    Data = apps.get_model('organizations', 'Progress')
    for name in ['начальный этап', 'давно в работе', 'завершен']:
        Data.objects.create(name=name, inserted_by_id=1,
                            inseted_at=dt.datetime.now)

class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0015_auto_20210713_0138'),
    ]

    operations = [
    ]
