# Generated by Django 3.2.5 on 2021-07-12 23:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0016_auto_20210713_0151'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='applicationscope',
            options={'verbose_name_plural': 'область применения'},
        ),
        migrations.AlterModelOptions(
            name='progress',
            options={'verbose_name_plural': 'Уровень прогресса'},
        ),
        migrations.AlterModelOptions(
            name='project',
            options={'verbose_name_plural': 'проекты'},
        ),
    ]
