# Generated by Django 3.2.5 on 2021-07-12 23:05

import datetime as dt

from django.db import migrations


def populate_progress(apps, schema_editor):
    Progress = apps.get_model('organizations', 'Progress')
    User = apps.get_model('auth', 'User')
    user = User.objects.get_or_create(username="admin")
    user.save()
    for name in ['начальный этап', 'давно в работе', 'завершен']:
        Progress.objects.create(name=name.capitalize(), inserted_by=user,
                            inserted_at=dt.datetime.now().isoformat())


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0017_auto_20210713_0205'),
    ]

    operations = [
        migrations.RunPython(populate_progress)
    ]
