# Generated by Django 3.2.5 on 2021-07-12 23:10

import datetime as dt

from django.db import migrations


def populate_progress(apps, schema_editor):
    Data = apps.get_model('organizations', 'EmployeeRole')
    User = apps.get_model('auth', 'User')
    user, _ = User.objects.get_or_create(username="admin")
    for name in ['Ведущий научный сотрудник']:
        Data.objects.create(name=name.capitalize(), inserted_by=user,
                            inserted_at=dt.datetime.now().isoformat())


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0018_auto_20210713_0205'),
    ]

    operations = [
        migrations.RunPython(populate_progress)
    ]
