# Generated by Django 3.2.5 on 2021-07-13 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0019_auto_20210713_0210'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='organization',
            name='city',
        ),
        migrations.AddField(
            model_name='organization',
            name='address',
            field=models.CharField(default='kwa kwa kwa', max_length=500, verbose_name='Адрес'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='City',
        ),
    ]
