# Generated by Django 3.2.5 on 2021-07-14 23:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('organizations', '0021_auto_20210714_1707'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='updated_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='updated_organization', to=settings.AUTH_USER_MODEL, verbose_name='Обновил'),
        ),
    ]
