# Generated by Django 3.2.5 on 2021-07-15 00:46

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0024_auto_20210715_0209'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='applicationscope',
            options={'verbose_name_plural': 'Область применения'},
        ),
        migrations.RemoveField(
            model_name='organization',
            name='updated_by',
        ),
        migrations.RemoveField(
            model_name='project',
            name='updated_by',
        ),
        migrations.AddField(
            model_name='applicationscope',
            name='updated_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Обновлено'),
        ),
        migrations.AddField(
            model_name='employee',
            name='updated_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Обновлено'),
        ),
        migrations.AddField(
            model_name='employeerole',
            name='updated_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Обновлено'),
        ),
        migrations.AddField(
            model_name='progress',
            name='updated_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Обновлено'),
        ),
    ]
