# Generated by Django 3.2.5 on 2021-07-15 01:17

import computed_property.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0025_auto_20210715_0346'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicationscope',
            name='updated_by',
            field=computed_property.fields.ComputedTextField(compute_from='_updated_by', default=1, editable=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='employee',
            name='updated_by',
            field=computed_property.fields.ComputedTextField(compute_from='_updated_by', default=1, editable=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='employeerole',
            name='updated_by',
            field=computed_property.fields.ComputedTextField(compute_from='_updated_by', default=1, editable=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='organization',
            name='updated_by',
            field=computed_property.fields.ComputedTextField(compute_from='_updated_by', default=1, editable=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='progress',
            name='updated_by',
            field=computed_property.fields.ComputedTextField(compute_from='_updated_by', default=1, editable=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='project',
            name='updated_by',
            field=computed_property.fields.ComputedTextField(compute_from='_updated_by', default=1, editable=False),
            preserve_default=False,
        ),
    ]
