# Generated by Django 3.2.5 on 2021-07-15 21:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('organizations', '0026_auto_20210715_0417'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicationscope',
            name='updated_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='organizations_applicationscope_related', to=settings.AUTH_USER_MODEL, verbose_name='Обновил'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='updated_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='organizations_employee_related', to=settings.AUTH_USER_MODEL, verbose_name='Обновил'),
        ),
        migrations.AlterField(
            model_name='employeerole',
            name='updated_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='organizations_employeerole_related', to=settings.AUTH_USER_MODEL, verbose_name='Обновил'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='updated_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='organizations_organization_related', to=settings.AUTH_USER_MODEL, verbose_name='Обновил'),
        ),
        migrations.AlterField(
            model_name='progress',
            name='updated_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='organizations_progress_related', to=settings.AUTH_USER_MODEL, verbose_name='Обновил'),
        ),
        migrations.AlterField(
            model_name='project',
            name='updated_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='organizations_project_related', to=settings.AUTH_USER_MODEL, verbose_name='Обновил'),
        ),
    ]
