# Generated by Django 3.2.5 on 2021-07-15 22:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0027_auto_20210716_0018'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='employee',
            unique_together={('first_name', 'last_name', 'degree')},
        ),
    ]
