# Generated by Django 3.2.5 on 2021-08-09 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0029_auto_20210716_2209'),
    ]

    operations = [
        migrations.AddField(
            model_name='country',
            name='alpha2',
            field=models.CharField(max_length=2, verbose_name='Alpha2'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='country',
            name='alpha3',
            field=models.CharField(max_length=3, verbose_name='Alpha3'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='country',
            name='english',
            field=models.CharField(max_length=500, verbose_name='На английском'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='country',
            name='fullname',
            field=models.CharField(max_length=500, verbose_name='Полное наименование'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='country',
            name='iso',
            field=models.IntegerField(verbose_name='ISO'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='country',
            name='location',
            field=models.CharField(max_length=500, verbose_name='Часть света'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='country',
            name='location_precise',
            field=models.CharField(max_length=500, verbose_name='Расположение'),
            preserve_default=False,
        ),
    ]
