# Generated by Django 3.2.5 on 2021-08-09 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0030_auto_20210809_1145'),
    ]

    operations = [
        migrations.AlterField(
            model_name='country',
            name='alpha2',
            field=models.CharField(blank=True, max_length=2, null=True, verbose_name='Alpha2'),
        ),
        migrations.AlterField(
            model_name='country',
            name='fullname',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Полное наименование'),
        ),
        migrations.AlterField(
            model_name='country',
            name='location',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Часть света'),
        ),
    ]
