# Generated by Django 3.2.5 on 2021-08-09 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0032_auto_20210809_1216'),
    ]

    operations = [
        migrations.AlterField(
            model_name='country',
            name='alpha2',
            field=models.CharField(blank=True, max_length=2, null=True, unique=True, verbose_name='Alpha2'),
        ),
        migrations.AlterField(
            model_name='country',
            name='alpha3',
            field=models.CharField(max_length=3, unique=True, verbose_name='Alpha3'),
        ),
        migrations.AlterField(
            model_name='country',
            name='english',
            field=models.CharField(max_length=500, unique=True, verbose_name='На английском'),
        ),
        migrations.AlterField(
            model_name='country',
            name='iso',
            field=models.IntegerField(unique=True, verbose_name='ISO'),
        ),
        migrations.AlterField(
            model_name='country',
            name='name',
            field=models.CharField(max_length=500, unique=True, verbose_name='Название'),
        ),
    ]
