# Generated by Django 3.2.5 on 2021-08-17 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0034_auto_20210809_1326'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='activity_description',
            field=models.TextField(blank=True, max_length=2048, null=True, verbose_name='Краткое описание вида деятельности'),
        ),
    ]
