# Generated by Django 3.2.5 on 2021-08-17 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0035_alter_organization_activity_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='field_of_activity',
            field=models.CharField(blank=True, choices=[('VM', 'Ветеринария'), ('RS', 'Исследования'), ('PD', 'Производство препаратов'), ('IP', 'Инновационные продукты на основе бактериофагов')], max_length=2, null=True),
        ),
    ]
