# Generated by Django 3.2.5 on 2021-08-17 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0036_organization_field_of_activity'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='products',
            field=models.TextField(blank=True, max_length=2048, null=True, verbose_name='Продукция'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='field_of_activity',
            field=models.CharField(blank=True, choices=[('VM', 'Ветеринария'), ('RS', 'Исследования'), ('PD', 'Производство препаратов'), ('IP', 'Инновационные продукты на основе бактериофагов')], max_length=2, null=True, verbose_name='Сфера деятельности'),
        ),
    ]
