# Generated by Django 3.2.6 on 2021-09-03 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0037_auto_20210817_1423'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='image',
            field=models.URLField(blank=True, null=True, verbose_name='Ссылка на изображение'),
        ),
    ]
