# Generated by Django 3.2.7 on 2021-09-06 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0038_organization_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='theme_is_dark',
            field=models.BooleanField(blank=True, max_length=50, null=True, verbose_name='Тема оформления карточки'),
        ),
    ]
