# Generated by Django 3.2.8 on 2021-10-28 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0039_organization_theme_is_dark'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='logo',
            field=models.URLField(blank=True, null=True, verbose_name='Cсылка на логотип'),
        ),
    ]
