# Generated by Django 3.2.8 on 2021-10-28 10:52

import colorfield.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0041_auto_20211028_0921'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='background_color',
            field=colorfield.fields.ColorField(blank=True, default=None, max_length=18, null=True),
        ),
    ]
