# Generated by Django 3.2.8 on 2021-10-28 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0042_organization_background_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='image',
            field=models.URLField(blank=True, max_length=500, null=True, verbose_name='Ссылка на изображение'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='logo',
            field=models.URLField(blank=True, max_length=500, null=True, verbose_name='Cсылка на логотип'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='theme_is_dark',
            field=models.BooleanField(blank=True, max_length=50, null=True, verbose_name='Тeмная тема оформления'),
        ),
    ]
