# Creating the dump of Database

- name: "Dump database {{ db_name }} to a file"
  postgresql_db:
    name: "{{ db_name }}"
    state: dump
    target: "/home/{{ app_owner }}/{{ ansible_date_time.date }}_{{ ansible_date_time.hour }}{{ ansible_date_time.minute }}.{{ ansible_date_time.second }}.sql"
    login_user: "{{ db_name }}"
    login_password: "{{ db_password }}"
    login_host: localhost
