# Generated by Django 3.2.10 on 2021-12-15 12:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500, verbose_name='Название')),
            ],
        ),
        migrations.CreateModel(
            name='CompanyBranch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500, verbose_name='Название')),
            ],
        ),
        migrations.CreateModel(
            name='Source',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1000, verbose_name='Название')),
            ],
        ),
        migrations.CreateModel(
            name='Strain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Supply',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sent_at', models.DateTimeField(blank=True, null=True, verbose_name='Предполагаемая дата отправки')),
                ('recieved_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата приема')),
                ('recieved_remark', models.CharField(blank=True, max_length=500, null=True, verbose_name='Примичание при приеме')),
                ('num', models.DateTimeField(blank=True, null=True, verbose_name='Предполагаемое количество')),
                ('dest', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='strains_supply.companybranch', verbose_name='Филиал')),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='strains_supply.source', verbose_name='Лечебное учреждение')),
                ('source_city', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='strains_supply.city', verbose_name='Город')),
            ],
        ),
        migrations.CreateModel(
            name='SupplyContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num', models.IntegerField(default=0)),
                ('strain_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='strains_supply.strain')),
                ('supply_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='strains_supply.supply')),
            ],
        ),
    ]
