# Generated by Django 3.2.10 on 2021-12-17 09:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('strains_supply', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='supply',
            name='source_city',
        ),
        migrations.AddField(
            model_name='source',
            name='city',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='strains_supply.city'),
            preserve_default=False,
        ),
    ]
