# Generated by Django 3.2.10 on 2021-12-20 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('strains_supply', '0004_auto_20211220_1014'),
    ]

    operations = [
        migrations.AddField(
            model_name='companybranch',
            name='alias',
            field=models.CharField(default='', max_length=500),
            preserve_default=False,
        ),
    ]
