# Generated by Django 3.2.10 on 2021-12-20 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('strains_supply', '0005_companybranch_alias'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companybranch',
            name='alias',
            field=models.CharField(max_length=500, unique=True),
        ),
    ]
