# Generated by Django 3.2.10 on 2021-12-20 15:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('strains_supply', '0007_auto_20211220_1804'),
    ]

    operations = [
        migrations.AddField(
            model_name='companybranch',
            name='inserted_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Добавлено'),
        ),
        migrations.AddField(
            model_name='companybranch',
            name='inserted_by',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='auth.user', verbose_name='Добавил'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='companybranch',
            name='updated_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Обновлено'),
        ),
        migrations.AddField(
            model_name='companybranch',
            name='updated_by',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='strains_supply_companybranch_related', to='auth.user', verbose_name='Обновил'),
            preserve_default=False,
        ),
    ]
