# Generated by Django 3.2.10 on 2021-12-21 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('strains_supply', '0008_auto_20211220_1806'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supply',
            name='num',
            field=models.IntegerField(blank=True, null=True, verbose_name='Предполагаемое количество'),
        ),
        migrations.AlterField(
            model_name='supply',
            name='sent_at',
            field=models.DateField(blank=True, null=True, verbose_name='Предполагаемая дата отправки'),
        ),
    ]
