# Generated by Django 3.2.10 on 2021-12-22 08:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('strains_supply', '0009_auto_20211221_1401'),
    ]

    operations = [
        migrations.RenameField(
            model_name='supply',
            old_name='num',
            new_name='suggested_num',
        ),
        migrations.RenameField(
            model_name='supply',
            old_name='sent_at',
            new_name='suggested_sent_date',
        ),
    ]
