# Generated by Django 3.2.10 on 2021-12-22 09:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('strains_supply', '0010_auto_20211222_1132'),
    ]

    operations = [
        migrations.RenameField(
            model_name='supply',
            old_name='recieved_at',
            new_name='received_at',
        ),
        migrations.RenameField(
            model_name='supply',
            old_name='recieved_remark',
            new_name='received_remark',
        ),
    ]
