# Generated by Django 3.2.10 on 2021-12-22 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('strains_supply', '0011_auto_20211222_1224'),
    ]

    operations = [
        migrations.AddField(
            model_name='supply',
            name='num',
            field=models.IntegerField(blank=True, null=True, verbose_name='Количество'),
        ),
        migrations.AddField(
            model_name='supply',
            name='sent_at',
            field=models.DateField(blank=True, null=True, verbose_name='Фактическа дата отправки'),
        ),
    ]
