# Generated by Django 3.2.10 on 2021-12-22 19:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('strains_supply', '0012_auto_20211222_1737'),
    ]

    operations = [
        migrations.RenameField(
            model_name='supplycontent',
            old_name='strain_id',
            new_name='strain',
        ),
        migrations.RenameField(
            model_name='supplycontent',
            old_name='supply_id',
            new_name='supply',
        ),
    ]
