# Generated by Django 3.2.10 on 2021-12-27 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('strains_supply', '0014_auto_20211223_1400'),
    ]

    operations = [
        migrations.CreateModel(
            name='BacteriaType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500, unique=True)),
                ('code', models.CharField(max_length=50, unique=True)),
            ],
        ),
    ]
