# Generated by Django 3.2.10 on 2021-12-27 06:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('strains_supply', '0015_bacteriatype'),
    ]

    operations = [
        migrations.CreateModel(
            name='BacteriaCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Название кода')),
            ],
        ),
        migrations.AlterField(
            model_name='bacteriatype',
            name='name',
            field=models.CharField(max_length=500, unique=True, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='bacteriatype',
            name='code',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='strains_supply.bacteriacode', verbose_name='Код'),
        ),
    ]
