# Generated by Django 3.2.10 on 2021-12-27 06:45

from django.db import migrations


def add_bacteria_types(apps, schema_editor):
    BacteriaCode = apps.get_model('strains_supply', 'BacteriaCode')
    BacteriaType = apps.get_model('strains_supply', 'BacteriaType')
    b_types = [
        "Кlebsiella pneumoniae", "Кlebsiella ozaenae",
        "Кlebsiella rhinoscleromatis", "Кlebsiella spp.",
        "Escherichiae соli", "Proteus mirabilis", "Proteus vulgaris",
        "Pseudomonas aeruginosa", "Staphylococcus aureus",
        "Staphylococcus epidermidis", "Streptococcus pneumoniae",
        "Streptococcus pyogenes", "Streptococcus (Enterococcus) faecalis",
        "Streptococcus  agalactiae", "Streptococcus spp", "Sh. sonnae",
        "Sh. flexneri 1,2,3,4,6 serotypes",
        "Sаlmonella spp. групп А, Б, С, Д, Е ",
        "Salmonella typhi (O и Vi)", "Acinetobacter baumanii",
        "Enterobacter aerogenes", "Enterobacter cloacаe",
        "Enterobacter agglomerans", "Кlebsiella oxitoca",
        "Enterococcus spp"
    ]
    code = BacteriaCode.objects.create(name='СВ Б1-25')
    code.save()
    for b_type in b_types:
        bt = BacteriaType.objects.create(name=b_type, code=code)
        bt.save()


class Migration(migrations.Migration):

    dependencies = [
        ('strains_supply', '0016_auto_20211227_0941'),
    ]

    operations = [migrations.RunPython(add_bacteria_types)]
