# Generated by Django 3.2.10 on 2021-12-27 07:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('strains_supply', '0018_auto_20211227_1000'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supplycontent',
            name='bacteria_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='strains_supply.bacteriatype', verbose_name='Наименование пробы'),
        ),
    ]
