# Generated by Django 3.2.10 on 2022-01-03 14:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('strains_supply', '0019_alter_supplycontent_bacteria_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='supply',
            name='deleted_at',
            field=models.DateField(blank=True, null=True, verbose_name='Дата удаления'),
        ),
        migrations.AddField(
            model_name='supply',
            name='deleted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='deleted_by', to=settings.AUTH_USER_MODEL, verbose_name='Удалил'),
        ),
        migrations.AddField(
            model_name='supply',
            name='deleted_remark',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Причина удаления'),
        ),
    ]
