---
- hosts: production
  user: "{{ ansible_ssh_user }}"
  become: yes
  become_user: root
  become_method: sudo

  vars_files:
    - external_vars.yaml

  tasks:
    - name: Set up environment variable for db
      lineinfile:
        dest: /etc/environment
        line: "SAVPY_DB_PASSWORD={{ db_password }}"
        state: present

    - name: Set up environment variable django app
      lineinfile:
        dest: /etc/environment
        line: "SECRET_KEY={{ secret_key }}"
        state: present

    - name: Set up environment variable django app (mode)
      lineinfile:
        dest: /etc/environment
        line: "DJANGO_ENV=PROD"
        state: present

    - name: Set up environment variable django app
      lineinfile:
        dest: /etc/environment
        line: "APP_HOST={{ inventory_hostname }}"
        state: present

    - name: Add nginx source repository into sources list
      apt_repository:
        repo: deb https://nginx.org/packages/ubuntu/ focal nginx
        state: present

    - name: Update apt cache
      apt: 
        update_cache: yes
        upgrade: yes

    - name: Install required packages
      apt:
        name:
          - python3-pip
          - python3-dev
          - libpq-dev
          - postgresql
          - postgresql-contrib
          - nginx
          - curl
          - gunicorn
          - acl
          - git

    - name: Install and create db
      include_tasks: ./tasks/create_db.yaml

    - name: Backup db
      include_tasks: ./tasks/backup_db.yaml

    # Installing python3.8 for ubuntu 18.04
    - name: install software-properties-common
      apt:
        name: software-properties-common

    - name: Add repository
      apt_repository:
        repo: ppa:deadsnakes/ppa

    - name: Install python3.8
      apt:
        name: python3.8
        update_cache: yes




    # Cloning project
    - name: Make dir for project
      file:
        path: "{{ app_path }}"
        state: directory
        owner: "{{ app_owner }}"
        group: www-data
        recurse: yes

    - name: Make dir for ssh
      file:
        path: /var/www/.ssh
        state: directory
        owner: "{{ app_owner }}"
        group: www-data
        recurse: yes

    - name: Get ssh_key_pub content
      shell: "cat /home/{{ app_owner }}/.ssh/id_rsa.pub"
      register: ssh_key_pub

    - name: Clone app from repository
      git:
        repo: "{{ git_repository }}"
        dest: "{{ app_path }}"
        version: "{{ git_branch }}"
      notify: Restart gunicorn

    # Creating a Python Virtual Environment for your Project
    - name: Install required python packages venv (global)
      pip:
        name:
          - virtualenv

    - name: Initiate virtualenv
      pip: virtualenv="{{ virtualenv_path }}"
           virtualenv_python=python3.8
           requirements={{ app_path }}/requirements.txt

    # Setting up Django
    - name: Initial migration
      django_manage:
        command: "migrate"
        app_path: "{{ app_path }}"
        virtualenv: "{{ virtualenv_path }}"
      notify: Create a superuser

    - name: Collect static
      django_manage:
        command: collectstatic
        app_path: "{{ app_path }}"
        virtualenv: "{{ virtualenv_path }}"


    # Elastic search
    # - name: Download elasticsearch
    #   get_url:
    #     url: https://artifacts.elastic.co/downloads/elasticsearch/elasticsearch-7.14.0-amd64.deb
    #     dest: /tmp/

    - name: Install Elastic search from the internet
      apt:
        deb: https://artifacts.elastic.co/downloads/elasticsearch/elasticsearch-7.14.0-amd64.deb
      notify: Start Elasticsearch

    - name: Creates a cron file under /etc/cron.d
      ansible.builtin.cron:
        name: update elasticsearch index
        minute: "*/1"
        job: "{{ virtualenv_path }}/bin/python {{ app_path }}/manage.py update_index"

    # Setting up Gunicorn and NGINX
    - name: Copy systemd socket file
      copy:
        src: ./configs/etc/systemd/system/gunicorn.socket
        dest: /etc/systemd/system/gunicorn.socket
      notify: Enable and start gunicorn

    - name: Copy systemd service file
      template:
        src: ./configs/etc/systemd/system/gunicorn.service.j2
        dest: /etc/systemd/system/gunicorn.service
      notify: Enable and start gunicorn

    - name: Copy nginx config file
      copy:
        src: ./configs/etc/nginx/nginx.conf
        dest: /etc/nginx/nginx.conf

    - name: Copy nginx site config file
      template:
        src: "./configs/etc/nginx/sites-available/{{ app_name }}.j2"
        dest: "/etc/nginx/sites-available/{{ app_name }}"

    - name: Create a symbolic link
      file:
        src: "/etc/nginx/sites-available/{{ app_name }}"
        dest: "/etc/nginx/sites-enabled/{{ app_name }}"
        owner: "{{ app_owner }}"
        group: www-data
        state: link
      notify: Restart nginx

    - name: Allow all access to 'Nginx Full'
      ufw:
        rule: allow
        name: 'Nginx Full'

  handlers:
    - name: Restart postgres
      service: name=postgresql state=restarted

    - name: Create a superuser
      django_manage:
        command: "createsuperuser --noinput --username={{django_admin_name}} --email={{django_admin_email}}"
        app_path: "{{ app_path }}"
        virtualenv: "{{ virtualenv_path }}"
      # python manage.py changepassword <user_name>

    - name: Start Elasticsearch
      shell: /etc/init.d/elasticsearch start

    - name: Enable and start gunicorn
      systemd:
        name: gunicorn
        state: started
        enabled: yes

    - name: Restart nginx
      systemd:
        name: nginx
        state: restarted

    - name: Restart gunicorn
      systemd:
        name: gunicorn
        state: restarted

